version: "3.8"

services:
  main:
    build: .
    container_name: discord-bot
    volumes:
      - discord-bot-data:/discord-bot/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PORTAINER_WEBHOOK=${PORTAINER_WEBHOOK}
    restart: unless-stopped

volumes:
  discord-bot-data:
    name: discord-bot-data